### ISSUE TITLE
After upgrading to eslint 9 I am getting a lot of warings of missing dependecy eslint 8.

### ISSUE THREAD

**Issue by PawelWozniak** [salesforce/eslint-config-lwc#130] opened 2024-05-02 08:41 UTC
Upgraded eslint to 9 and in the command line I got those warnings:

`npm warn ERESOLVE overriding peer dependency
npm warn While resolving: salesforce-app@1.0.0
npm warn Found: eslint@8.57.0
npm warn node_modules/eslint
npm warn   dev eslint@"^9.1.1" from the root project
npm warn   16 more (@babel/eslint-parser, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^7 || ^8" from @lwc/eslint-plugin-lwc@1.8.1
npm warn node_modules/@lwc/eslint-plugin-lwc
npm warn   dev @lwc/eslint-plugin-lwc@"^1.8.1" from the root project
npm warn   1 more (@salesforce/eslint-config-lwc)
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: salesforce-app@1.0.0
npm warn Found: eslint@8.57.0
npm warn node_modules/eslint
npm warn   dev eslint@"^9.1.1" from the root project
npm warn   16 more (@babel/eslint-parser, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^7 || ^8" from @lwc/eslint-plugin-lwc@1.8.1
npm warn node_modules/@lwc/eslint-plugin-lwc
npm warn   dev @lwc/eslint-plugin-lwc@"^1.8.1" from the root project
npm warn   1 more (@salesforce/eslint-config-lwc)
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: salesforce-app@1.0.0
npm warn Found: eslint@8.57.0
npm warn node_modules/eslint
npm warn   dev eslint@"^9.1.1" from the root project
npm warn   16 more (@babel/eslint-parser, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^7 || ^8" from @salesforce/eslint-config-lwc@3.5.3
npm warn node_modules/@salesforce/eslint-config-lwc
npm warn   dev @salesforce/eslint-config-lwc@"^3.5.3" from the root project
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: salesforce-app@1.0.0
npm warn Found: eslint@8.57.0
npm warn node_modules/eslint
npm warn   dev eslint@"^9.1.1" from the root project
npm warn   16 more (@babel/eslint-parser, ...)`

Restored 8.57 and is fine. 
Please add support for new version.

**Comment by nolanlawson** [comment] 2024-05-06 20:24
Hi, we do not support ESLint v9 yet. Sorry about that!

**Comment by nolanlawson** [comment] 2024-05-06 20:24
Closing as a duplicate of https://github.com/salesforce/eslint-config-lwc/issues/128

**Closed by nolanlawson** 2024-05-06 20:24 UTC
